# Ethereal theme
name = "Ethereal"
appearance = "dark"

# Core colors
foreground = "#ffcead"
background = "#060B1E"
cursor = "#ffcead"
cursor_text = "#060B1E"
selection_background = "#ffcead"
selection_foreground = "#060B1E"
accent = "#7d82d9"

# Normal colors (0-7)
color0 = "#060B1E"
color1 = "#ED5B5A"
color2 = "#92a593"
color3 = "#E9BB4F"
color4 = "#7d82d9"
color5 = "#c89dc1"
color6 = "#a3bfd1"
color7 = "#F99957"

# Bright colors (8-15)
color8 = "#6d7db6"
color9 = "#faaaa9"
color10 = "#c4cfc4"
color11 = "#f7dc9c"
color12 = "#c2c4f0"
color13 = "#ead7e7"
color14 = "#dfeaf0"
color15 = "#ffcead"

# UI colors
ui_border = "#7d82d9"
ui_border_secondary = "#6d7db6"
ui_border_faint = "#060B1E"
ui_selected = "#6d7db6"
ui_match = "#E9BB4F"
ui_gray = "#6d7db6"

# App-specific theme names
nvim_colorscheme = "ethereal"
