# Hackerman theme
name = "Hackerman"
appearance = "dark"

# Core colors
foreground = "#ddf7ff"
background = "#0B0C16"
cursor = "#ddf7ff"
cursor_text = "#0B0C16"
selection_background = "#ddf7ff"
selection_foreground = "#0B0C16"
accent = "#82FB9C"

# Normal colors (0-7)
color0 = "#0B0C16"
color1 = "#50f872"
color2 = "#4fe88f"
color3 = "#50f7d4"
color4 = "#829dd4"
color5 = "#86a7df"
color6 = "#7cf8f7"
color7 = "#85E1FB"

# Bright colors (8-15)
color8 = "#6a6e95"
color9 = "#85ff9d"
color10 = "#9cf7c2"
color11 = "#a4ffec"
color12 = "#c4d2ed"
color13 = "#cddbf4"
color14 = "#d1fffe"
color15 = "#ddf7ff"

# UI colors
ui_border = "#82FB9C"
ui_border_secondary = "#6a6e95"
ui_border_faint = "#0B0C16"
ui_selected = "#6a6e95"
ui_match = "#50f7d4"
ui_gray = "#6a6e95"

# App-specific theme names
nvim_colorscheme = "hackerman"
